version: '3'

services:
  web:
    restart: always
    build: .
    #command: python hello.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: securepass